//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLCategory()
        {
            this.TBLBook = new HashSet<TBLBook>();
        }
    
        public byte CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDetail { get; set; }
        public Nullable<bool> CategoryStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBook> TBLBook { get; set; }
    }
}
